version: "3"
# Dev DB for PG Kernel
services:
  db:
    image: postgres:15
    volumes:
    - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
    - "5432:5432"
### DEV App
#  app:
#    links:
#      - db
#    image: elschnagoo/xserver:latest
#    env_file:
#      - .env
#    volumes:
#      - ./backend/data:/app/data
#      - ./backend/.env/data:/app/.env
#      - ./backend/src/data:/app/src
#    ports:
#      - "9257:9257"

